### ISSUE TITLE
Deploy as github pages

### ISSUE THREAD

**Issue by joshmoore** [zarr-developers/community-calls#2]
This repo could potentially be deployed similar to https://github.com/zarr-developers/blog so that all pages are accessible via https://zarr.dev/community-calls though that might have an impact on how we structure the subdirectories.

cc: @MSanKeys963

**Comment by MSanKeys963** [comment]
I'm all for it. Any suitable template for https://zarr.dev/community-calls you can think of? Or do you wanna use the one from [blog](https://github.com/zarr-developers/blog) or [zeps](https://github.com/zarr-developers/zeps)?

**Comment by joshmoore** [comment]
> Is any suitable template for https://zarr.dev/community-calls you can think of?

Not off hand.

> Or do you wanna use the one from [blog](https://github.com/zarr-developers/blog) or [zeps](https://github.com/zarr-developers/zeps)?

both are probably ok, but probably with year subdirectories, eh?

**Comment by MSanKeys963** [comment]
> both are probably ok, but probably with year subdirectories, eh?

I think [Just the Docs](https://just-the-docs.github.io/just-the-docs/) would be suitable in this case. I'll start working on the deployment soon.

**Comment by MSanKeys963** [comment]
Done in #5.
