### ISSUE TITLE
Update calendar to include bi-weekly Zarr-python refactor standup

### ISSUE THREAD

**Issue by jhamman** [zarr-developers/community-calls#24]
We have decided to have a 30 minute bi-weekly standup meeting to track progress on the Zarr-python refactor working group (https://github.com/zarr-developers/zarr-python/discussions/1480). 

This meeting is scheduled for 9a PT. The first meeting should be set for September 6th, 2023 and repeated every 2 weeks until the end of 2023.

@MSanKeys963 - do you need additional information to make this happen?

**Comment by MSanKeys963** [comment]
Thanks for the kick-off meeting, @jhamman.
I've added the bi-weekly standup meeting to the Zarr Community Calendar starting 09/06.

Please see here: https://zarr.dev/community-calls/.
